
function getSpecificText() {
    window.alert("This is me");
    document.write("I'm in Hack.js");
    var name = document.querySelector("#propulsion-name"); {
            if (name === "Electric") {
        document.write("The electric propulsion system is a popular technology used on rockets and satellites due to its high specific impulse while carrying less propellant versus chemical propulsion systems (Choueiri, 2009). However, the main disadvantage of an electric propulsion system is that it is unsuitable for launches from the Earth’s surface (due to its small thrust). There are three main types of electric propulsion systems: electrostatic, electrothermal, and electromagnetic. Each type uses a different energy source to generate acceleration of the plasma ions (O'Reilly, Herdrich, & Kavanagh, 2021). Due to the use of electrical power to accelerate a rocket, the distance that an electric propulsion rocket travels is much further than chemical propulsion systems with the same amount of propellant. The reason behind this is due to its unique way of creating thrust which is different to chemical propulsion systems. Certain propulsion systems emit heavy gases such as xenon to create thrust. A propulsion system that companies such as NASA and SpaceX are thinking about using is an ion propulsion system. Ion thruster, an electric propulsion system, is currently being used by NASA to keep geosynchronous Earth orbit communication satellites in their desired locations. For example, the Dawn spacecraft, which used an ion propulsion system, continued to accelerate for 11 years before running out of fuel (Wall, 2018).");
        if (name === "Nuclear") {
        document.write("The nuclear propulsion system for spacecrafts is a theory that was created half a century ago. But rockets with a nuclear propulsion system has never been developed due to the high risk of spreading radioactive debris in the event of an accident. Nuclear rocket engines either use a solid core system or a fluid core system. The solid core system is very similar to the traditional liquid propulsion system; the only part that has changed is that the combustion chamber 4 has been replaced by a reactor (Poston, 2021). The nuclear electric propulsion generates electricity through a nuclear reactor and transfer it to electric thrusters to create an exhaust velocity (Bennet, 2021). A nuclear thermal propulsion system is considered to have a high exhaust velocity and a high specific impulse (Dunbar, Nuclear Propulsion Could Help Get Humans to Mars Faster, 2021). The reason scientists and engineers investigated the possibility of a nuclear propulsion system is due to its high thrust and high specific impulse. This would allow for an increase in interplanetary trips while decreasing the duration of each trip.");
    }
        if (name === "Chemical") {
        document.write("In a solid propellant propulsion system, propellant is a mixture of fuel and oxidizer in solid form. This allows the rocket to be more stable and simpler, while it still exhibits consistent performance across ignition systems. But this type of propulsion system causes the propellant to burn until all the fuel has been exhausted out through the nozzle. Solid rocket propulsion systems are considered to be less efficient than hybrid or liquid engines (Nancy Hall, 2021). However, solid propulsion systems do have their share of advantages. They are known to be compact and are smaller in comparison to the traditional liquid rocket. This allows for a greater amount of cargo to be part of the rocket. Also, solid propulsion systems have a high thrust to weight ratio allowing for a greater acceleration than other types of propulsion systems. This Thrust to Weight Ratio can be seen through the equation: Ratio = F/W = Thrust/Weight = (mass*acceleration)/(mass* graviatiational acceleration) = acceleration/gravitation acceleration The graviatiational acceleration is a constant of 9.8 m/s^2 Since the gravitational acceleration is a constant, the larger the acceleration of the rocket, the greater the thrust to weight ratio. Additionally, the thrust to weight ratio must be greater than 1 for the rocket to accelerate upward. However, the solid propulsion system has a relatively low specific impulse in comparison to a liquid propulsion system. As solid propulsion systems are known to burn their propellant at a predictive rate, it makes it easier for scientists to calculate the necessary amount of fuel to reach the desired location.");
    } else
        alert("Please type one of the following propulsion systems: Chemical, Electric, or Nuclear ");

    }
    } 
}


 /*
function getSpecificText() {
    const SpecificText = document.querySelector("#propulsion-name").value;
    if (SpecificText === Electric) {
        console.log("The electric propulsion system is a popular technology used on rockets and satellites due to its high specific impulse while carrying less propellant versus chemical propulsion systems (Choueiri, 2009). However, the main disadvantage of an electric propulsion system is that it is unsuitable for launches from the Earth’s surface (due to its small thrust). There are three main types of electric propulsion systems: electrostatic, electrothermal, and electromagnetic. Each type uses a different energy source to generate acceleration of the plasma ions (O'Reilly, Herdrich, & Kavanagh, 2021). Due to the use of electrical power to accelerate a rocket, the distance that an electric propulsion rocket travels is much further than chemical propulsion systems with the same amount of propellant. The reason behind this is due to its unique way of creating thrust which is different to chemical propulsion systems. Certain propulsion systems emit heavy gases such as xenon to create thrust. A propulsion system that companies such as NASA and SpaceX are thinking about using is an ion propulsion system. Ion thruster, an electric propulsion system, is currently being used by NASA to keep geosynchronous Earth orbit communication satellites in their desired locations. For example, the Dawn spacecraft, which used an ion propulsion system, continued to accelerate for 11 years before running out of fuel (Wall, 2018).");
    if (SpecificText === Nuclear) {
        console.log("The nuclear propulsion system for spacecrafts is a theory that was created half a century ago. But rockets with a nuclear propulsion system has never been developed due to the high risk of spreading radioactive debris in the event of an accident. Nuclear rocket engines either use a solid core system or a fluid core system. The solid core system is very similar to the traditional liquid propulsion system; the only part that has changed is that the combustion chamber 4 has been replaced by a reactor (Poston, 2021). The nuclear electric propulsion generates electricity through a nuclear reactor and transfer it to electric thrusters to create an exhaust velocity (Bennet, 2021). A nuclear thermal propulsion system is considered to have a high exhaust velocity and a high specific impulse (Dunbar, Nuclear Propulsion Could Help Get Humans to Mars Faster, 2021). The reason scientists and engineers investigated the possibility of a nuclear propulsion system is due to its high thrust and high specific impulse. This would allow for an increase in interplanetary trips while decreasing the duration of each trip.");
    }
    if (SpecificText === Chemical) {
        console.log("In a solid propellant propulsion system, propellant is a mixture of fuel and oxidizer in solid form. This allows the rocket to be more stable and simpler, while it still exhibits consistent performance across ignition systems. But this type of propulsion system causes the propellant to burn until all the fuel has been exhausted out through the nozzle. Solid rocket propulsion systems are considered to be less efficient than hybrid or liquid engines (Nancy Hall, 2021). However, solid propulsion systems do have their share of advantages. They are known to be compact and are smaller in comparison to the traditional liquid rocket. This allows for a greater amount of cargo to be part of the rocket. Also, solid propulsion systems have a high thrust to weight ratio allowing for a greater acceleration than other types of propulsion systems. This Thrust to Weight Ratio can be seen through the equation: Ratio = F/W = Thrust/Weight = (mass*acceleration)/(mass* graviatiational acceleration) = acceleration/gravitation acceleration The graviatiational acceleration is a constant of 9.8 m/s^2 Since the gravitational acceleration is a constant, the larger the acceleration of the rocket, the greater the thrust to weight ratio. Additionally, the thrust to weight ratio must be greater than 1 for the rocket to accelerate upward. However, the solid propulsion system has a relatively low specific impulse in comparison to a liquid propulsion system. As solid propulsion systems are known to burn their propellant at a predictive rate, it makes it easier for scientists to calculate the necessary amount of fuel to reach the desired location.");
    } else
        alert("Please type one of the following propulsion systems: Chemical, Electric, or Nuclear ");
    }
}
*/